module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "blue-600": "var(--blue-600)",
        "blue-gray100": "var(--blue-gray100)",
        "blue-gray200": "var(--blue-gray200)",
        "blue-gray300": "var(--blue-gray300)",
        "blue-gray600": "var(--blue-gray600)",
        "blue-gray900": "var(--blue-gray900)",
        bodycolour: "var(--bodycolour)",
        defaultalert: "var(--defaultalert)",
        defaultwhite: "var(--defaultwhite)",
        "green-100": "var(--green-100)",
        "green-500": "var(--green-500)",
        "green-800": "var(--green-800)",
        "orange-600": "var(--orange-600)",
        "purple-100": "var(--purple-100)",
        "purple-400": "var(--purple-400)",
        "purple-600": "var(--purple-600)",
        "purple-800": "var(--purple-800)",
        "violet-600": "var(--violet-600)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        body: "var(--body-font-family)",
        "body-l": "var(--body-l-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-s": "var(--body-s-font-family)",
        "body-XS": "var(--body-XS-font-family)",
        "button-m": "var(--button-m-font-family)",
        "button-XL": "var(--button-XL-font-family)",
        "caption-m": "var(--caption-m-font-family)",
        h3: "var(--h3-font-family)",
        h4: "var(--h4-font-family)",
        heading: "var(--heading-font-family)",
        "heading-1-m": "var(--heading-1-m-font-family)",
        "heading-2": "var(--heading-2-font-family)",
        "heading-6": "var(--heading-6-font-family)",
        "subtitle-m": "var(--subtitle-m-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        bgdrop: "var(--bgdrop)",
        "button-shadow": "var(--button-shadow)",
        "shadow-dark-s": "var(--shadow-dark-s)",
        "shadow-dark-XL": "var(--shadow-dark-XL)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
